name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
        - os: windows-latest
          generator: "Visual Studio 17"
          name: "rtype_win"
          update-profile: false
        - os: ubuntu-latest
          generator: "Unix Makefiles"
          name: "rtype_linux"
          conanOptions: " -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True"
          update-profile: true
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0

    - name: Cache .conan
      id: cache-conan
      uses: actions/cache@v3
      env:
        cache-name: cache-conan
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
          ${{ runner.os }}-conan-
          ${{ runner.os }}-
        

    - name: Create default profile
      if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
      run: conan profile new default --detect

    - name: Update profile
      if: ${{ matrix.update-profile == 'true' }}
      run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --install-folder=${{github.workspace}}/build --build=missing ${{matrix.conanOptions}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{matrix.generator}}"

    - name: Builds
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}
        path: ${{github.workspace}}/bin
